export interface SquareObject {
    compatibility: number | null,
    highlight: boolean,
    type: string,
    plantArea: boolean,
    coordinates?: number[]
}

export const plantTypes : any = {
    nothing: [],
Basil: {
    Oregano: 2,
    Peppers: 2,
    Sage: 1,
    Thyme: 1,
    Tomatoes: 2
  },
  Beans: {
    Broccoli: 2,
    Carrots: 2,
    Cauliflower: 2,
    Chives: -2,
    Corn: 2,
    Cucumbers: 2,
    Garlic: -2,
    Leeks: -2,
    Marigold: -2,
    Onion: -2,
    Peas: 2,
    Peppers: -2,
    Rosemary: 2,
    Sage: 1,
    Strawberry: 2,
    'Swiss Chard': 2,
    Thyme: 1,
    Tomatoes: 2
  },
  Broccoli: {
    Beans: 2,
    Carrots: 2,
    Chives: 2,
    Cucumbers: 2,
    Dill: 2,
    Garlic: 2,
    Lettuce: 2,
    Nasturtium: 2,
    Onion: 2,
    Oregano: 3,
    Peppers: -2,
    Rosemary: 2,
    Sage: 2,
    Spinach: 2,
    Squash: -2,
    Strawberry: -2,
    'Swiss Chard': 2,
    Thyme: 2,
    Tomatoes: -2
  },
  Carrots: {
    Beans: 2,
    Broccoli: 2,
    Cauliflower: 2,
    Chives: 2,
    Dill: -2,
    Leeks: 2,
    Lettuce: 2,
    Onion: 2,
    Parsley: 2,
    Peas: 2,
    Peppers: 2,
    Rosemary: 2,
    Sage: 2,
    Thyme: 1,
    Tomatoes: -1
  },
  Cauliflower: {
    Beans: 2,
    Carrots: 2,
    Chives: 2,
    Cucumbers: 2,
    Dill: 2,
    Garlic: 2,
    Lettuce: 2,
    Nasturtium: 2,
    Onion: 2,
    Oregano: 3,
    Peppers: -2,
    Rosemary: 2,
    Sage: 2,
    Spinach: 2,
    Squash: -2,
    Strawberry: -2,
    'Swiss Chard': 2,
    Thyme: 2,
    Tomatoes: -2
  },
  Chives: {
    Beans: -2,
    Broccoli: 2,
    Carrots: 2,
    Cauliflower: 2,
    Parsley: 2,
    Peas: -2,
    Sage: 1,
    Thyme: 1,
    Tomatoes: 2
  },
  Cilantro: {
    Sage: 1,
    Spinach: 2,
    Thyme: 1
  },
  Corn: {
    Beans: 2,
    Cucumbers: 2,
    Dill: 2,
    Melon: 2,
    Parsley: 2,
    Peas: 2,
    Sage: 1,
    Squash: 2,
    Sunflower: 2,
    Thyme: 1,
    Tomatoes: -2
  },
  Cucumbers: {
    Beans: 2,
    Broccoli: 2,
    Cauliflower: 2,
    Corn: 2,
    Dill: 2,
    Lettuce: 2,
    Nasturtium: 2,
    Onion: 2,
    Peas: 2,
    Peppers: 2,
    Sage: -2,
    Thyme: 1,
    Tomatoes: 2
  },
  Dill: {
    Broccoli: 2,
    Carrots: -2,
    Cauliflower: 2,
    Corn: 2,
    Cucumbers: 2,
    Lettuce: 2,
    Onion: 2,
    Sage: 1,
    Thyme: 1,
    Tomatoes: -2
  },
  Garlic: {
    Beans: -2,
    Broccoli: 2,
    Cauliflower: 2,
    Lettuce: 2,
    Peas: -2,
    Sage: 1,
    Strawberry: 2,
    Thyme: 1,
    Tomatoes: 2
  },
  Leeks: {
    Beans: -2,
    Carrots: 2,
    Onion: 2,
    Peas: -2,
    Sage: 1,
    Spinach: 2,
    Thyme: 1
  },
  Lettuce: {
    Broccoli: 2,
    Carrots: 2,
    Cauliflower: 2,
    Cucumbers: 2,
    Dill: 2,
    Garlic: 2,
    Onion: 2,
    Sage: 1,
    Spinach: 2,
    Squash: 2,
    Strawberry: 2,
    Thyme: 1,
    Tomatoes: 2
  },
  Marigold: {
    Beans: -2,
    Melon: 2,
    Sage: 1,
    Squash: 3,
    Thyme: 1,
    Tomatoes: 2
  },
  Melon: {
    Corn: 2,
    Marigold: 2,
    Nasturtium: 2,
    Sage: 1,
    Squash: 2,
    Sunflower: 2,
    Thyme: 1
  },
  Nasturtium: {
    Broccoli: 2,
    Cauliflower: 2,
    Cucumbers: 2,
    Melon: 2,
    Sage: 1,
    Squash: 3,
    Thyme: 1,
    Tomatoes: 2
  },
  Onion: {
    Beans: -2,
    Broccoli: 2,
    Carrots: 2,
    Cauliflower: 2,
    Cucumbers: 2,
    Dill: 2,
    Leeks: 2,
    Lettuce: 2,
    Parsley: 2,
    Peas: -2,
    Sage: 1,
    Strawberry: 2,
    'Swiss Chard': 2,
    Thyme: 1,
    Tomatoes: 2
  },
  Oregano: {
    Broccoli: 3,
    Cauliflower: 3,
    Peppers: 2,
    Sage: 1,
    Thyme: 1
  },
  Parsley: {
    Carrots: 2,
    Chives: 2,
    Corn: 2,
    Onion: 2,
    Peas: 2,
    Peppers: 2,
    Sage: 1,
    Thyme: 1,
    Tomatoes: 2
  },
  Peas: {
    Beans: 2,
    Carrots: 2,
    Chives: -2,
    Corn: 2,
    Cucumbers: 2,
    Garlic: -2,
    Leeks: -2,
    Onion: -2,
    Parsley: 2,
    Peppers: 2,
    Sage: 1,
    Spinach: 2,
    Squash: 2,
    Strawberry: 2,
    Thyme: 1
  },
  Peppers: {
    Beans: -2,
    Broccoli: -2,
    Carrots: 2,
    Cauliflower: -2,
    Cucumbers: 2,
    Oregano: 2,
    Parsley: 2,
    Peas: 2,
    Rosemary: 2,
    Sage: 1,
    Squash: 2,
    'Swiss Chard': 2,
    Thyme: 1,
    Tomatoes: 2
  },
  Rosemary: {
    Beans: 2,
    Broccoli: 2,
    Carrots: 2,
    Cauliflower: 2,
    Peppers: 2,
    Sage: 1,
    Thyme: 1
  },
  Sage: {
    Beans: 1,
    Broccoli: 2,
    Carrots: 2,
    Cauliflower: 2,
    Chives: 1,
    Cilantro: 1,
    Corn: 1,
    Cucumbers: -2,
    Dill: 1,
    Garlic: 1,
    Leeks: 1,
    Lettuce: 1,
    Marigold: 1,
    Melon: 1,
    Nasturtium: 1,
    Onion: 1,
    Oregano: 1,
    Parsley: 1,
    Peas: 1,
    Peppers: 1,
    Rosemary: 1,
    Spinach: 1,
    Squash: 1,
    Strawberry: 1,
    Sunflower: 1,
    'Swiss Chard': 1,
    Thyme: 1,
    Tomatoes: 1
  },
  Spinach: {
    Broccoli: 2,
    Cauliflower: 2,
    Cilantro: 3,
    Leeks: 2,
    Lettuce: 2,
    Peas: 2,
    Sage: 1,
    Strawberry: 2,
    Thyme: 1
  },
  Squash: {
    Broccoli: -2,
    Cauliflower: -2,
    Corn: 2,
    Lettuce: 2,
    Marigold: 3,
    Melon: 2,
    Nasturtium: 3,
    Peas: 2,
    Peppers: 2,
    Sage: 1,
    Thyme: 1
  },
  Strawberry: {
    Beans: 2,
    Broccoli: -2,
    Cauliflower: 2,
    Garlic: 2,
    Lettuce: 2,
    Onion: 2,
    Peas: 2,
    Sage: 1,
    Spinach: 2,
    Thyme: 2
  },
  Sunflower: {
    Corn: 2,
    Melon: 2,
    Sage: 1,
    Thyme: 1
  },
  'Swiss Chard': {
    Beans: 2,
    Broccoli: 2,
    Cauliflower: 2,
    Onion: 2,
    Peppers: 2,
    Sage: 1,
    Thyme: 1
  },
  Thyme: {
    Beans: 1,
    Broccoli: 2,
    Carrots: 1,
    Cauliflower: 2,
    Chives: 1,
    Cilantro: 1,
    Corn: 1,
    Cucumbers: 1,
    Dill: 1,
    Garlic: 1,
    Leeks: 1,
    Lettuce: 1,
    Marigold: 1,
    Melon: 1,
    Nasturtium: 1,
    Onion: 1,
    Oregano: 1,
    Parsley: 1,
    Peas: 1,
    Peppers: 1,
    Rosemary: 1,
    Sage: 1,
    Spinach: 1,
    Squash: 1,
    Strawberry: 2,
    Sunflower: 1,
    'Swiss Chard': 1,
    Tomatoes: 1
  },
  Tomatoes: {
    Beans: 2,
    Broccoli: -2,
    Carrots: -1,
    Cauliflower: -2,
    Chives: 2,
    Corn: -2,
    Cucumber: 2,
    Dill: -2,
    Garlic: 2,
    Lettuce: 2,
    Marigold: 2,
    Nasturtium: 2,
    Onion: 2,
    Parsley: 2,
    Peppers: 2,
    Sage: 1,
    Thyme: 1
  }
}